Generated pb case statements not camelized enough (#1363)
Problem:

protobuf fields that 1) are defined in a oneof and 2) have underscores as part of their name
do not compile when generated:

```
[error] /Users/esbie/workspace/linkerd/grpc/eg/target/scala-2.12/src_managed/main/compiled_protobuf/io/buoyant/eg/Eg.pb.scala:215: value Ok_response is not a member of object io.buoyant.eg.Eg.Message.OneofResult
[error]           case Some(Message.OneofResult.`Ok_response`(value)) =>
[error]                                         ^
[error] /Users/esbie/workspace/linkerd/grpc/eg/target/scala-2.12/src_managed/main/compiled_protobuf/io/buoyant/eg/Eg.pb.scala:248: value Ok_response is not a member of object io.buoyant.eg.Eg.Message.OneofResult
[error]           case Some(Message.OneofResult.Ok_response(value)) =>
[error]                                         ^
[error] two errors found
```

Solution: Add more camels
Validation: Added to EgTest